Binaryify/NeteaseCloudMusicApi

- .gitignore
- app.js
- package.json
1. 把express.static的路径改成绝对路径,防止在使用pm2部署的时候由于cwd不确定产生static文件404的问题
2. npm在安装依赖的时候自动把package.json中的数组展开成多行的格式, 建议按照npm默认的格式来维护package.json
3. 在.gitignore文件中添加了一些项, 方便使用IDEA编辑器的小伙伴共同开发
> 修复了express.static的路径问题

- router/playlist_detail.js
我发现了获取歌单详情似乎出现了问题，在获取到的数据内tracks内部最多只有10首歌，然后有一个trackIds的数组，其数量虽然完整，但内部只有两个信息，一个歌曲的ID，还有一个不知道什么东西。
```js
"trackIds": [
{
"id": 28283308,
"v": 10
},
// 整体长度正常但是信息缺失
]
```
于是我寻找到了这个看上去挺老的接口 不过可以正常工作
另外对node的request模块不是很熟悉，不知道为啥换成get回复参数不正确，就干脆暴力的在路径后面加query了
> fix: playlist-detail api can't get all tracks , update source api

- router/banner.js
对于第三方客户端的项目，banner接口还是非常重要的
然而v2.8.0(用request重写请求)更新中给banner接口随缘增加参数绝对是不行的😂
从`/discover`页取数据的神奇操作
来源于[pureliumy/NeteaseMusicBanner](https://github.com/pureliumy/NeteaseMusicBanner)
我将提取的过程换用正则做了
Q: 为什么不用`util.js`里封装好的`createRequest`
A: 因为`randomUserAgent`如果取到移动端UA会重定向到M站，获取不到数据
Q: 为什么等人找参数PR不现实
A: 请求都走网页版weapi，然而banner的旧接口是客户端api。用weapi的加密方式去请求，再怎么改参数也没有意义啊。且现在客户端都走eapi接口，去逆向旧接口的价值不大
Q: 为什么我一直没PR
A: 因为这样改有缺陷，网页版的banner的尺寸(730x336)，而且不是专辑封面那样可以带`?param=`来控制尺寸的，与旧接口相比小一圈，也请作者权衡后merge
> banner接口修改

- app.js
`fs` 读取目录获得的文件名数组， `login.js` 排在 `loginCellphone.js` 前面
所以会先注册 `/login` 这个路径，导致后面注册的 `login/cellphone` 无法被正确处理
> fix: 手机登陆异常

- app.js
使用相对路径会导致在非项目根目录执行 app.js 会报错, 例如在项目目录外一层执行 `node NeteaseCloudMusicApi/app.js`
```
Error: ENOENT: no such file or directory, scandir './router/'
```
所以改用绝对路径
> 使用绝对路径读取路由文件注册

- .gitignore
- app.js
- package.json
- yarn.lock
移除对 `npmview` 的依赖 . 使用`node` 原生的模块 `child_process` 的 `exec` 方法进行版本对比
>对于 执行时候 报错： **Request path contains unescaped characters**  
的解决方法为：设置 `npm config set registry http://registry.npmjs.org/` , `https ----> http`
> Remove npmview dependency

- docs/README.md
- module/album_newest.js
- module/scrobble.js
1. `/top/album`新碟上架与首页数据不一致，新增接口`/album/newest`
2. 包装`/weblog`调用，新增接口`/scrobble`更新听歌记录
> 获取首页新碟上架数据以及更新听歌排行

- module/video_group.js
该接口仅在eapi中提供，经测试，可以通过 weapi返回。常见的使用场景: 
1. 根据视频ID获取到videoGroup
2. 根据videoGroupId获取到相关的视频。
（该接口需要登录后才可使用)
具体使用方式: `http://localhost:3000/video/group?id=9104`
> 增加视频标签下的视频获取

- module/activate_init_profile.js
- module/cellphone_existence_check.js
> 验证手机是否注册、验证用户名是否注册

- module/playlist_desc_update.js
- module/playlist_name_update.js
- module/playlist_tags_update.js
- module/search_default.js
抓包的时候看到了默认搜索关键词的 API
歌单的信息名和描述都有合法性校验，感觉还是分开来比较好，要是能有头像上传那就非常好了
都是 eapi 的
> 默认搜索关键词、单独的歌单名，描述，标签更新

- app.js
fix #564
因预检 (OPTIONS) 请求没有 body
不带参请求网易云服务器返回 400 参数错误
以及内部在 undefined 上 split，hash 请出错返回 500
无法通过预检而无法跨域
解决方法：在中间件直接返回预检成功，不 next() 到路由处理请求
测试用例
```js
fetch('http://localhost:3000/song/url', {
method: 'POST',
mode: 'cors',
credentials: 'include',
headers: {'content-type': 'application/json'},
body: JSON.stringify({id: 347230})
})
```
> 支持 CORS 预检

- docs/README.md
- module/cellphone_existence_check.js
> add countrycode for cellphone check

- package.json
刚才更新的给 nodejs 的发布包可以砍掉一些不必要的内容。
本地可以通过 `npm pack` 预览提供给 npm 发布的 package。
> chore: optimize the publishing package for npm

- .gitignore
- README.MD
- public/avatar_update.html
- public/index.html
- public/playlist_cover_update.html
- public/test.html
- util/request.js
RT 本来只更新了下UA的 后面发现随机UA的函数问题很大，所以就优化了下
相关代码在 /util/request.js
> 更新 UA 列表，更改随机 UA 相关逻辑

- util/index.js
此次更新 types 文件后，对应布尔值的地方允许使用了 type: `boolean`，而接口对布尔参数的处理是调用的 `toBoolean`。
此方法目前只会检查 string ` true` `1`，并不会处理 boolean 类型。
例如： `toBoolean(true) => false`， 因此此 Patch 是对该问题的一个快捷修正
> 修复与 types 文件表现不一致问题

- app.js
- docs/README.md
- module/homepage_dragon_ball.js
- module/simi_artist.js
- module/song_url.js
1. 在调用模块前，若`req.query.cookie`和`req.body.cookie`是字符串，则先解码，再转为对象。
2. 删除在各模块中的转换。
3. 更新文档。
> 解决使用POST请求时cookie没有转换为对象导致的问题

- app.js
A regular expression that can require polynomial time to match may be vulnerable to denial-of-service attacks.
Some regular expressions take a long time to match certain input strings to the point where the time it takes to match a string of length n is proportional to nk or even 2n. Such regular expressions can negatively affect performance, or even allow a malicious user to perform a Denial of Service ("DoS") attack by crafting an expensive input string for the regular expression to match.
>  Polynomial regular expression

- app.js
The patched split regex wouldn't handle the given cookie correctly.
Assume given `__remember_me=true; MUSIC_U=aaaaaadddddd; __csrf=ddddddddddd; NMTID=fffffffff` as request cookie, by using `^\s+|(?<!\s)\s+$` it wouldn't contain 3 matches and result 4 entries
> Fix the wrong cookie split regex

- plugins/songUpload.js
Before:
1. The real upload error will be swallowed
2. The request will fail when music file is greater than 10MB
After:
Both issues are fixed
Test:
`node song_upload.js`
> Better Error Handling for Upload Failure and Max Uploading File Length

- main.js
- main.test.js
- package.json
- server.js
將原本 "NeteaseCloudMusicApi/server" 掃描 modules 目錄的部分抽出 server.js，
改移到 main.js。這樣使用者就有辦法只載入靜態的伺服器部分（不動態載入模組）。
這個 patch 的 breaking changes 不易發生。可作為 patch version 發佈。
> refactor: allow using server statically

- package.json
目前的 NPM 包少了 server.js，會導致 "NeteaseCloudMusicApi/server" 找不到檔案，也會讓 `npx NeteaseCloudMusicApi` 報錯（找不到 server.js 模組）
> fix: add "server.js" to the filelist to pack

- public/index.html
Vercel部署，Nginx反代到子路径下。
部署在https://meedfine.com/music-api/ 
原代码会导致首页示例调用到 错误路径 https://meedfine.com/comment/music?id=186016&limit=1   404
调整后正常：https://meedfine.com/music-api/comment/music?id=186016&limit=1
调整成 根路径与子路径都支持
> fix: 部署在域名子路径下无法执行示例的问题

- .github/workflows/node.js.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .dockerignore
- Dockerfile
目前的 Dockerfile 有如下几个问题：
1. `COPY` 命令复制了全部源码，很多是在实际 Docker 运行中用不到的，会增加镜像体积
2. `npm config set registry` 应该是不需要的，使用 github action 打包镜像时 npm install 速度足够快
3. `npm i --omit=dev --ignore-scripts` 可以替换 `npm install -g husky && npm install --production`
4. **严重问题：** 使用 `CMD ["node", "app.js"]` 会导致 nodejs 无法及时响应操作系统传递的信号，具体表现为执行 `docker stop` 命令停止容器时耗时很久，可以参考 https://dev.to/nodepractices/docker-best-practices-with-node-js-4ln4
重构后的 Dockerfile 有如下提升：
1. 镜像体积在 dockerhub 由原来的 76.23M 缩减为 56.33M
2. 可以瞬时响应 `docker stop` 命令
注意：`.dockerignore` 文件中以 `!/` 开头的文件代表了会拷贝进 Docker 镜像的文件（更好的做法是重新调整源码目录结构，比如增加 src 目录，这样编写 Dockerfile 会更简洁）
> Dockerfile 重构

- package-lock.json
- package.json
- util/request.js
在一个使用 ESM 的 Electron 项目上，运行时报错 axios is not a function
然后发现在[这个 commit](https://github.com/Binaryify/NeteaseCloudMusicApi/commit/23516ca856270ad04871399e1d4c494f07901780#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) 里将 axios 的版本升级到了 1.0.0，在 axios 新版本的文档上提到过 CommonJS 中可以使用这种写法来导入：
```
const axios = require('axios').default
``` 
实测这样导入可以解决 ESM 中的问题。如果直接转换成 ESM，导入的 axios 就成了一个 module，没办法直接作为函数使用，而使用里面默认导出的 default 函数就可以了。
另外 `const { default: axios } = require('axios')` 也等价于上面的写法，这样写只是为了美观一点。
> fix: axios is not a function when using ES module

- docs/README.md
加入对新歌词接口 `/song/lyric/v1` 中 `yrc` 字段的解释
同时[`pyncm`中也有相关impl](https://github.com/mos9527/pyncm/blob/master/pyncm/utils/yrcparser.py)以`ass`格式输出卡拉ok式歌词。写的有点难看就没加在README里了🫤
> docs: document `yrc` lyrics

- interface.d.ts
类型从 `/song/detail?ids=28884496` 接口的响应内容和 https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1121#issuecomment-774438040 整理的字段说明结合而来。
我眼下需要使用 song_details 接口的返回值，因此只为这一个接口添加了类型
> refactor(dts): 更新 song_detail 返回值类型

- package-lock.json
- package.json
- util/request.js
- yarn.lock
`pac-proxy-agent` 5.0.0 - 6.0.4 的引用中使用了存在安全风险且停止维护的 `vm2` 。
更新到 7.0.0 可解决此问题。
ref:
https://github.com/patriksimek/vm2/security
https://github.com/TooTallNate/proxy-agents/releases/tag/degenerator%405.0.0
P.S. 同时更新了 npm 与 yarn 的 lock 文件。
> Fix security risk with deprecated vm2 dependency

- interface.d.ts
同步 #1760 和 #1731 中对 `level` 参数的修改
> refactor: Sync TypeScript Definition of /song/url/v1

- module/song_url.js
修复了使用 Node.js 调用 song_url 时，如 `id` 参数传入类型为 `number` 时，则会发生的错误：
```
TypeError: query.id.split is not a function
```
> Fix: 使用 Node 调用 song_url 时未正确处理 number 类型

- .github/workflows/Build_Image.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command
