Binaryify/NeteaseCloudMusicApi

README.MD
build/app.js
build/component/getPlaylists
src/app.js
src/component/getPlaylists.js
test/test.js

Add getPlaylists

---

docs/README.md

document mistakes

---

router/login.js
router/loginCellphone.js
router/login_refresh.js

上次只改了手机登录的cookie 没有更改刷新登录的cookie

修改Domain  cookie 丢失问题

---

Dockerfile
README.MD

Docker Hub镜像首页：https://hub.docker.com/r/pengxiao/netease-music-api/

增加Dockerfile，支持以Docker容器模式运行。

---

Dockerfile
docs/README.md
package.json

1. 修复了docker cloud自动构建失败的问题, 可以下docker cloud上自动构建镜像了
2. 更新了使用文档中docker的启动命令处版本号的问题

修复了docker自动构建的一些问题, 更新了文档

---

app.js
router/send_playlist.js
router/send_text.js

增加私信功能
send_playlist
send_text
分别是私信文字和私信歌单
其中参数user_ids为接受人，可为多人，例如[user_id1, user_id2]这种形式，单人也必须为数组
参数msg表示私信内容
send_playlist多一个参数playlist表示发送的歌单，填入playlist的id即可
另：对于邮箱登录有相应的解决方案，还有其他接口也可以提供

private msg

---

router/comment_hot.js
router/comment_like.js
util/util.js

1.修复非法参数403 #335
调整了顺序 先取proxy再取csrfToken
2. 修复代理错误 #334
将os=pc放到了cookie的最前边

修复非法参数403 #335, 修复代理错误 #334

---

util/request.js

fix #364 rm debug 

---

module/search_suggest.js

更新 搜索建议 接口

---

docs/README.md
module/login_cellphone.js
package.json
util/request.js

Usage:
https://github.com/trazyn/ieaseMusic/blob/master/server/api.js#L81

Add pac proxy support

---

app.js

Added customizable host.
Use 'HOST=0.0.0.0 node app.js' to listen on all ip's.

Added customizable host.

---

module/user_record.js

🐞fix(user_record): fix type always be 1

---

module/homepage_block_page.js
module/homepage_dragon_ball.js

新增移动端 首页发现页 接口

---

app.test.js
main.d.ts
package-lock.json
package.json
test/album.test.js
test/comment.test.js
test/login.test.js
test/lyric.test.js
test/music_url.test.js
test/search.test.js
util/request.js

考虑到`request`已经`deprecated`，而项目又已经引入了`axios`，所以使用`axios`代替`request`。并没有测试所有`api`，不过大部分都是可用的。
现在的问题是关于`eapi`的部分，原先的响应处理似乎不需要，这部分还请作者检查一下。
还有缓存部分，我没有细看，不过应该是可以正常使用。

使用axios代替request

---

module/homepage_dragon_ball.js
module/simi_artist.js

引入`config.json`时加上拓展名，防止打包软件报错

🐞fix: import config with ext

---

module/playlist_tracks.js

Fix playlist_tracks

---

public/cloud.html

云盘上传做成了可以批量上传，还稍微调整了一下
1. 支持多选批量上传
2. 失败自动重新上传（3次）
3. 删除上传类型限制（格式太多了，audio/* 都匹配不完）
4. 修复了密码有+之类的特殊符号导致的登录失败

feat: Batch upload

---

app.js

After Chrome 80, the default samesite in cookie will be set to `Lax`.
And i am try to fix it. Disable SameSite policy when deploy by tls.
For more detail about Chrome 80, checkout:
- https://support.google.com/chrome/a/thread/27911174/chrome-80-release-notes-are-now-live?hl=en
- https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html
For more detail about SameSite, checkout:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

fix: samesite problem in cors request after chrome 80

---

README.MD

Update README.MD 添加第三方SDK板块

---

app.js

Hi, 增加这句注释后，你发布时node.js就会进行处理，之后别人通过npm i -g 全局安装后，就可直接在命令行输入NeteaseCloudMusicApi运行服务端。

增加二进制文件node标识

---

plugins/songUpload.js

use replace rather than replaceAll

fix(plugins-songUpload): compatibility method

---

util/config.json

请求时默认带上匿名帐号的 cookie，大量的使用者会导致接收到“操作频繁”响应，影响使用。
新增一个提示，提示用户在 util/config.json 中更换为自己的cookie。
这是我第一次 pull request，虽然修改的地方很简单，但还是非常希望能够参与到该开源项目中来。

chore: Modify the config.json and prompt the user to bring their own cookies

---

docs/README.md
module/song_url_v1.js

注意, 为防止兼容性问题, 仍然保留旧版 API
新版 API 不再使用 br 作为音质的区分而是通过 standard 等单词更加准确地获取指定音质
默认 level 暂未设置

[feat] 新增新版 音乐链接获取 API

---

docs/README.md

修正一处文档 URL 错误
当时可能抓包调试地脑袋一团浆糊, URL 这个写错了

[typo]<doc>: 修正文档错误

---

module_example/multi_song_upload.js

Make a function to upload so we can reuse it when reuploading failed files.
Also fix single file upload (when passing `--file`), it was not treated as array properly.

feat: auto retry failed upload (in module_example)

---

module/login_cellphone.js
package-lock.json

fix: 修复了手机号登录接口

---

.github/workflows/DockerHub-Description.yml

当 README.MD 更新时自动同步 Github ReadMe 到 DockerHub

同步 Github ReadMe 到 DockerHub

---

.gitignore
package.json

- 修复依赖缺失导致打包后无法执行
- 消除打包时 `Warning Failed to make bytecode`
相关 #1657

解决 pkg 打包后无法运行

---

docs/README.md
module/starpick_comments_summary.js

[feat] 新增星评馆简要评论获取

---

module/check_music.js

检查音频时即然能返回音频是否可用，个人觉得将 code: 200 返回会比较合理点，在调用时也会方便不少

check_music add code  :wheelchair:

---

module/song_url_v1.js

移除了song_url_v1中的console.log，在自己代码里面找了半天这个log是哪来的最后发现是在这个库里...

[fix] removed unnecessary console log in song_url_v1

---

plugins/songUpload.js

update: song upload use up-to-date ip

---

README.MD

将我为此项目创建的Python SDK添加到了SDK列表 [NeteaseCloudMusic_PythonSDK](https://github.com/2061360308/NeteaseCloudMusic_PythonSDK)

And Python SDK in README.MD
